version: '3.8'

services:
  # Poste.io для домена стримкэш.рф
  mail:
    image: analogic/poste.io
    container_name: streamcash_mail
    restart: unless-stopped
    hostname: mail.xn--h1aefoeg0czb.xn--p1ai
    ports:
      - "8090:80"   # HTTP админка (доступ через nginx proxy)
      - "25:25"     # SMTP
      - "110:110"   # POP3
      - "143:143"   # IMAP
      - "587:587"   # SMTP submission
      - "993:993"   # IMAPS
      - "995:995"   # POP3S
    environment:
      - HTTPS=OFF  # SSL терминация через nginx
      - DISABLE_CLAMAV=true
      - VIRTUAL_HOST=mail.стримкэш.рф
      - VIRTUAL_PORT=80
    volumes:
      - mail_data:/data
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - streamcash_network

  # Nginx proxy для SSL терминации почты
  nginx-mail:
    image: nginx:alpine
    container_name: streamcash_nginx_mail
    restart: unless-stopped
    ports:
      - "8443:443"  # HTTPS для mail админки
    volumes:
      - ./nginx/nginx.mail.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mail
    networks:
      - streamcash_network
    profiles:
      - production

  # Альтернатива для разработки - Mailhog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: streamcash_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - streamcash_network
    profiles:
      - dev

volumes:
  mail_data:

networks:
  streamcash_network:
    external: true